### ISSUE TITLE
Can't install in portable project targeting .NET Framework 4.6 / Windows Universal 10.0

### ISSUE THREAD

**Issue by DunetsNM** [StephenCleary/CalculatedProperties#1]
Getting the error:

Package Nito.CalculatedProperties 1.0.0 is not compatible with dnxcore50 (DNXCore,Version=v5.0). Package Nito.CalculatedProperties 1.0.0 supports: portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)

**Comment by StephenCleary** [comment]
`dnxcore50` is a [deprecated framework](https://docs.nuget.org/ndocs/schema/target-frameworks), and will not be supported.

I created a new PCL targeting .NET Framework 4.6 and Windows Universal 10.0, and was able to install `Nito.CalculatedProperties` 1.0.0 successfully. I also tested installing `Nito.Mvvm.CalculatedProperties` 1.0.0-eta-01, and that also worked.

I suspect your PCL was built using prerelease technologies and still has a `dnxcore50` target, which should be removed.
